site_name: Machinable
site_url: https://machinable.io
repo_url: https://github.com/machinable
repo_name: 'machinable'
site_author: Nick Sjostrom
# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Nick Sjostrom'
nav:
  - Overview: 'index.md'
  - Getting Started: 'getting_started.md'
  - Release Notes: 'release_notes.md'
  - About: 'about.md'
  - Projects:
    - 'API Resources': 'projects/resources.md'
    - 'Collections': 'projects/collections.md'
    - 'Access': 'projects/access.md'
    - 'Security': 'projects/security.md'
    - 'Settings': 'projects/settings.md'
  - Querying:
    - 'Manage Data': 'querying_data/crud.md'
    - 'Pagination': 'querying_data/pagination.md'
    - 'Filtering': 'querying_data/filtering.md'
    - 'Sorting': 'querying_data/sorting.md'
  - Account:
    - 'Contact': 'account/contact.md'
    - 'Password Reset': 'account/password.md'
    - 'Billing & Plans': 'account/billing.md'
    - 'Security': 'account/security.md'
    - 'API Keys': 'account/apikeys.md'
    - 'Support': 'account/support.md'
  - Reference:
    - 'JSON Schema': 'reference/json_schema.md'
    - 'Sample Projects': 'reference/sample_projects.md'
  - API:
    - 'Machinable API': 'api/introduction.md'
theme: 
  name: 'material'
  feature:
    tabs: true
  palette:
    primary: 'blue grey'
extra_css:
  - 'styles.css'
markdown_extensions:  
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.toc:
      permalink: true